# Generated by Django 4.2 on 2023-09-17 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان')),
                ('one_body', models.CharField(blank=True, max_length=1000, null=True, verbose_name='متن اولیه')),
                ('do_you_know', models.CharField(blank=True, max_length=1000, null=True, verbose_name='آیا میدانید')),
                ('two_body', models.CharField(blank=True, max_length=1000, null=True, verbose_name='متن دوم')),
                ('image', models.ImageField(upload_to='image/articles', verbose_name='درج عکس اصلی')),
                ('image1', models.ImageField(null=True, upload_to='image/articles', verbose_name='درج عکس 1')),
                ('image2', models.ImageField(null=True, upload_to='image/articles', verbose_name='درج عکس 2')),
                ('image3', models.ImageField(null=True, upload_to='image/articles', verbose_name='درج عکس 3')),
                ('date', models.DateField(auto_now=True, null=True, verbose_name='زمان انتشار')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='دکتر')),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسندگان',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.article', verbose_name='مقاله')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='لایک کننده')),
            ],
            options={
                'verbose_name': 'لایک',
                'verbose_name_plural': 'لایک ها',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.author', verbose_name='نویسنده'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(null=True, to='blog.category', verbose_name='دسته بندی'),
        ),
    ]
