# Generated by Django 4.2 on 2023-09-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrSaeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=1000, null=True, verbose_name='بیوگرافی')),
                ('image', models.ImageField(upload_to='dr_Saeed')),
                ('resume', models.ImageField(upload_to='dr_Saeed/resume')),
                ('resume1', models.ImageField(upload_to='dr_Saeed/resume')),
                ('resume2', models.ImageField(upload_to='dr_Saeed/resume')),
                ('resume3', models.ImageField(upload_to='dr_Saeed/resume')),
                ('resume4', models.ImageField(upload_to='dr_Saeed/resume')),
                ('resume5', models.ImageField(upload_to='dr_Saeed/resume')),
            ],
            options={
                'verbose_name': 'دکتر سعید',
                'verbose_name_plural': 'دکتر سعید',
            },
        ),
        migrations.CreateModel(
            name='DrTahereh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=1000, null=True, verbose_name='بیوگرافی')),
                ('image', models.ImageField(upload_to='dr_tahereh')),
                ('resume', models.ImageField(upload_to='dr_tahereh/resume')),
                ('resume1', models.ImageField(upload_to='dr_tahereh/resume')),
                ('resume2', models.ImageField(upload_to='dr_tahereh/resume')),
                ('resume3', models.ImageField(upload_to='dr_tahereh/resume')),
                ('resume4', models.ImageField(upload_to='dr_tahereh/resume')),
                ('resume5', models.ImageField(upload_to='dr_tahereh/resume')),
            ],
            options={
                'verbose_name': 'دکتر طاهره',
                'verbose_name_plural': 'دکتر طاهره',
            },
        ),
    ]
