# Generated by Django 4.2 on 2023-09-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='نام کامل')),
                ('phone', models.CharField(max_length=11, null=True, verbose_name=' تلفن همراه')),
                ('message', models.TextField(max_length=400, verbose_name='متن پیام')),
            ],
            options={
                'verbose_name': 'پیغام',
                'verbose_name_plural': 'پیغام ها',
            },
        ),
    ]
